version: "3.8"
services:
	mariadb:
    container_name: mariadb
    image: mariadb:inception
    build: ./requirements/mariadb
    restart: unless stopped
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE} # From .env
      MYSQL_USER: ${MYSQL_USER}  # From .env
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
      MYSQL_PASSWORD_FILE: /run/secrets/db_password
    volumes:
      - type: bind
        source: ./data/mariadb
        target: /var/lib/mysql
    network:
      - backend
    secrets:
      - mysql_root_password
      - mysql_password

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    restart: unless-stopped
    environment:
      WP_DB_HOST: mariadb:3306
      WP_DB_NAME: ${MYSQL_DATABASE}
      WP_DB_USER: ${MYSQL_USER}
      WP_DB_PASSWORD_FILE: /run/secrets/db_password
      WP_TITLE: "Inception Project"
    env_file:
      - .env
    volumes:
      - type: bind
        source: ./data/wordpress
        target: /var/www/html
    # This tells dockercompose to wait for another container to start before starting this service
    depends_on:
      - mariadb
    networks:
      - frontend
      - backend
    secrets:
      - mysql_password

  nginx:
    container_name: nginx
    build: ./requirements/nginx
    restart: unless-stopped
    envirnoment:
      DOMAIN_NAME: ${DOMAIN_NAME}
    depends_on:
      - wordpress
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - frontend
    ports:
      - "443:443"

# Secret definitions
secrets:
  mysql_root_password:
    file: ./secrets/db_root_password.txt
  mysql_password:
    file: ./secrets/db_password.txt

# Network definitions
networks:
  frontend: # public facing
  backend: # internal communication