version: "3.8"
services:
	mariadb:
    container_name: mariadb
    image: mariadb:inception
    build: ./requirements/mariadb
    init: true # needed?
    restart: unless stopped
    environment: # if we have vars inside the container used by the script
    volumes: # more verbose preferred with the below options for diff volumes
    - type:
      source:
      target:
    network:
    secrets:
      - mysql_root_password
      - mysql_password


#  wordpress:
#    build: ./requirements/wordpress
#    container_name: wordpress
#    restart: unless-stopped
#    env_file:
#      - .env
#    secrets:
#      - mysql_password
#    depends_on:
#      - mariadb
#    networks:
#      - frontend
#      - backend
#    ports:

#  nginx:
#    build: ./requirements/nginx
#    container_name: nginx
#    restart: unless-stopped
#    ports:
#      - "443:443"
#    depends_on:
#      - wordpress
#    volumes:
#     - type: bind
#        source: ./requirements/nginx/conf
#        target: /etc/nginx/conf.d
#    networks:
#      - frontend
#    ports:

secrets:
  mysql_root_password:
    file: ./secrets/db_root_password.txt
  mysql_password:
    file: ./secrets/db_password.txt

volumes:
  mariadb_data:

networks:
  frontend:
  backend:

# at the end, can we have custom networks like this, for better control for which
# services can talk to which?
# networks:
#   -frontend: -> for services that don't require to be connected to the db? nginx + wordpress
#   -backend: -> where the rest of the servives are connected to the db? mariadb + wordpress

# depends on: -> for wordpress and nginx
# ports -> needed only for nginx and WP
# that tells dockercompose to wait for another container to start before starting this service