# Draft - Basic commands
# Base image to build from; using the penultimate stable version of Debian, Bookworm 12
FROM --platform linux/amd64 debian:bookworm-slim
# Install dependencies
RUN update && apt install nginx ~Y