NAME: inception

# DOCKER COMPOSE COMMANDS

# compose-build: -> build containers
# 	docker compose build

# compose-up: -> run containers
#	docker compose up

# compose-up-built: -build & run
#	docker compose up --build

# compose-down
#	docker compose down